version: 0.2

env:
    LOGIN: "a95ad9141e9eeb9d77ad06b52d353369f9167faf"
    HOST: "https://sonarcloud.io"
    Organization: "prajwalsr7"
    Project: "prajwalsr7_travel1"
phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - yum update -y
      - yum install -y jq
      - retry_count=3
      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && break || sleep 10; done
      - tar xzf apache-maven-3.5.4-bin.tar.gz || true
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
  build:
    commands:
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=prajwalsr7_travel1 -Dsonar.organization=prajwalsr7 || true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=prajwalsr7_travel1 >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
artifacts:
  files:
    - '**/*'